import type { Lugar, ParamsPresupuesto, TestSeis } from "./tipos";

// Sessions que On Air ya hizo. Los pines marcados como no confirmados
// estan puestos a ojo: arrastralos o editá lat/lng desde la ficha.
export const LUGARES_SEMILLA: Lugar[] = [
  {
    id: "capuchinos",
    nombre: "Iglesia de los Capuchinos",
    ciudad: "Córdoba",
    provincia: "Córdoba",
    pais: "Argentina",
    lat: -31.4275,
    lng: -64.1866,
    ubicacionConfirmada: true,
    categoria: "iglesia",
    tipo: "publico",
    estado: "hecha",
    notas: "Session filmada. Está en el canal.",
    creadoEn: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "ecu-rosario",
    nombre: "ECU, Espacio Cultural Universitario UNR",
    ciudad: "Rosario",
    provincia: "Santa Fe",
    pais: "Argentina",
    lat: -32.9468,
    lng: -60.636,
    ubicacionConfirmada: true,
    categoria: "universidad",
    tipo: "publico",
    estado: "hecha",
    notas:
      "Dos días con la UNR en agosto de 2025: Forum abierto y fiesta. Declaración de interés del Concejo. Es la plantilla del modelo con institución.",
    creadoEn: "2025-08-01T00:00:00.000Z",
  },
  {
    id: "cultivo-la-rioja",
    nombre: "Cultivo en La Rioja",
    ciudad: "La Rioja",
    provincia: "La Rioja",
    pais: "Argentina",
    lat: -29.4135,
    lng: -66.8558,
    ubicacionConfirmada: false,
    categoria: "cultivo",
    tipo: "privado",
    estado: "hecha",
    notas: "Session filmada. Pin a ojo, corregilo.",
    creadoEn: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "boeing-737",
    nombre: "Boeing 737",
    ciudad: "Córdoba",
    provincia: "Córdoba",
    pais: "Argentina",
    lat: -31.31,
    lng: -64.21,
    ubicacionConfirmada: false,
    categoria: "avión",
    tipo: "privado",
    estado: "hecha",
    notas: "Session filmada adentro del avión. Pin a ojo, corregilo.",
    creadoEn: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "las-palapas",
    nombre: "Las Palapas",
    ciudad: "Villa Carlos Paz",
    provincia: "Córdoba",
    pais: "Argentina",
    lat: -31.42,
    lng: -64.5,
    ubicacionConfirmada: false,
    categoria: "aire libre",
    tipo: "privado",
    estado: "hecha",
    notas: "Session filmada. Pin a ojo, corregilo.",
    creadoEn: "2024-01-01T00:00:00.000Z",
  },
];

export const CATEGORIAS = [
  "avión",
  "iglesia",
  "cultivo",
  "universidad",
  "museo",
  "bodega",
  "estancia",
  "castillo",
  "dique",
  "salina",
  "mina",
  "observatorio",
  "hangar",
  "estadio vacío",
  "tren",
  "barco",
  "termas",
  "aire libre",
  "otro",
];

export const PARAMS_DEFAULT: ParamsPresupuesto = {
  capacidad: 800,
  ocupacion: 0.85,
  precioEntrada: 25000,
  tipoCambio: 1500,
  tipoLugar: "publico",
  internacional: true,
  cachetCubierto: false,
  rentalCanje: true,
  locacionCanje: true,
  barraPropia: true,
  ticketingPct: 0.1,
  derechosPct: 0.18,
};

export const TEST_VACIO: TestSeis = {
  dueno: "",
  artefacto: "",
  fecha: "",
  aQuien: "",
  queCambia: "",
  queQueda: "",
};
